### ISSUE TITLE
docker image error

### ISSUE THREAD

**Issue by spyshow** [mrmn2/PdfDing#32]
when i make a docker compose ( or  a docker run) the docker contaier run but it give an error:
```
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [17] [CRITICAL] WORKER TIMEOUT (pid:24)
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [17] [CRITICAL] WORKER TIMEOUT (pid:26)
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [24] [ERROR] Error handling request (no URI read)
2024-12-18 15:22:10 Traceback (most recent call last):
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
2024-12-18 15:22:10     req = next(parser)
2024-12-18 15:22:10           ^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
2024-12-18 15:22:10     self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
2024-12-18 15:22:10                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
2024-12-18 15:22:10     super().__init__(cfg, unreader, peer_addr)
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
2024-12-18 15:22:10     unused = self.parse(self.unreader)
2024-12-18 15:22:10              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
2024-12-18 15:22:10     line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
2024-12-18 15:22:10                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
2024-12-18 15:22:10     self.get_data(unreader, buf)
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
2024-12-18 15:22:10     data = unreader.read()
2024-12-18 15:22:10            ^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
2024-12-18 15:22:10     d = self.chunk()
2024-12-18 15:22:10         ^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
2024-12-18 15:22:10     return self.sock.recv(self.mxchunk)
2024-12-18 15:22:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
2024-12-18 15:22:10     sys.exit(1)
2024-12-18 15:22:10 SystemExit: 1
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [26] [ERROR] Error handling request (no URI read)
2024-12-18 15:22:10 Traceback (most recent call last):
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
2024-12-18 15:22:10     req = next(parser)
2024-12-18 15:22:10           ^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
2024-12-18 15:22:10     self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
2024-12-18 15:22:10                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
2024-12-18 15:22:10     super().__init__(cfg, unreader, peer_addr)
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
2024-12-18 15:22:10     unused = self.parse(self.unreader)
2024-12-18 15:22:10              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 274, in parse
2024-12-18 15:22:10     line, rbuf = self.read_line(unreader, buf, self.limit_request_line)
2024-12-18 15:22:10                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 326, in read_line
2024-12-18 15:22:10     self.get_data(unreader, buf)
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
2024-12-18 15:22:10     data = unreader.read()
2024-12-18 15:22:10            ^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
2024-12-18 15:22:10     d = self.chunk()
2024-12-18 15:22:10         ^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
2024-12-18 15:22:10     return self.sock.recv(self.mxchunk)
2024-12-18 15:22:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-18 15:22:10   File "/home/nonroot/.venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
2024-12-18 15:22:10     sys.exit(1)
2024-12-18 15:22:10 SystemExit: 1
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [24] [INFO] Worker exiting (pid: 24)
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [26] [INFO] Worker exiting (pid: 26)
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [17] [ERROR] Worker (pid:24) was sent SIGKILL! Perhaps out of memory?
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [27] [INFO] Booting worker with pid: 27
2024-12-18 15:22:10 [2024-12-18 12:22:10 +0000] [28] [INFO] Booting worker with pid: 28
```

my docker compose file :
```
services:
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    volumes:
      - sqlite_data:/home/nonroot/pdfding/db
      - media:/home/nonroot/pdfding/media
      # If you use selinux it might be necessary to add the :Z after the volume
      # - sqlite_data:/home/nonroot/pdfding/db:Z
      # - media:/home/nonroot/pdfding/media:Z
    environment:
      HOST_NAME: "*"
      SECRET_KEY: og6XXQHkgeDBixqufzyhVU6FZtaWWlcb
      ACCOUNT_EMAIL_VERIFICATION: FALSE
      DISABLE_USER_SIGNUP: FALSE #or TRUE
      CSRF_COOKIE_SECURE: FALSE
      SESSION_COOKIE_SECURE: FALSE
      SECURE_SSL_REDIRECT: TRUE
    ports:
      - 8000:8000

volumes:
  sqlite_data:
  media:
```

**Comment by mrmn2** [comment]
Hm, I just tried it with your `compose` file. On my end this setups works without any problem while accessing via `localhost` and `127.0.0.1`. 

Could you provide me with more info about your setup? Are you using a reverse proxy or anything else noteworthy?  

Does this error appear when you start the compose stack, or only when you are visiting certain sites or are performing special actions?

**Comment by spyshow** [comment]
I am using docker on a Windows machine.
the error appears when I start the container and visit http://localhost:8000

**Comment by mrmn2** [comment]
Before I find someone to reproduce the issue on a windows machine, can you verify that you encounter the same problem when using this `compose` file:

```
version: '3'

services:
  pdfding:
    container_name: pdfding
    image: mrmn/pdfding:latest
    volumes:
      - sqlite_data:/home/nonroot/pdfding/db
      - media:/home/nonroot/pdfding/media
    environment:
      SECRET_KEY: some_secret
      HOST_NAME: 127.0.0.1
      # In production set to TRUE
      CSRF_COOKIE_SECURE: 'FALSE'
      # In production set to TRUE
      SESSION_COOKIE_SECURE: 'FALSE'
    ports:
      - "8000:8000"

volumes:
  sqlite_data:
  media:
```

Once it is up and running try visiting `http://127.0.0.1:8000`. Are you encountering the same problem?

**Comment by spyshow** [comment]
it worked if i put http://127.0.0.1:8000 but gave the same error If I put http://localhost:8000

thanks

**Comment by mrmn2** [comment]
You're welcome.

PS: If you like PdfDing it would be great if you could star the repo!
