### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 

### ISSUE THREAD

**Issue by econcepcion** [mrmn2/PdfDing#52]
Just installed in docker.  using docker-compose file provided.

postgres.docker-compose.yaml

I am getting this error when i try to submit a pdf.

Thanks

--------------------------------------------------------------------------------

Internal Server Error: /pdf/add

Traceback (most recent call last):

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

               ^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view

    return self.dispatch(request, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch

    return handler(request, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/pdfding/base/base_views.py", line 29, in post

    self.obj_save(form, request, identifier)

  File "/home/nonroot/pdfding/pdf/views/pdf_views.py", line 45, in obj_save

    pdf.save()  # we need to save otherwise the file will not be found in the next step

    ^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 892, in save

    self.save_base(

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 998, in save_base

    updated = self._save_table(

              ^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1161, in _save_table

    results = self._do_insert(

              ^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1202, in _do_insert

    return manager._insert(

           ^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1835, in execute_sql

    for sql, params in self.as_sql():

                       ^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1760, in as_sql

    self.prepare_value(field, self.pre_save_val(field, obj))

                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1708, in pre_save_val

    return field.pre_save(obj, add=True)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/fields/files.py", line 338, in pre_save

    file.save(file.name, file.file, save=False)

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/db/models/fields/files.py", line 99, in save

    self.name = self.storage.save(name, content, max_length=self.field.max_length)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/core/files/storage/base.py", line 49, in save

    name = self._save(name, content)

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/nonroot/.venv/lib/python3.12/site-packages/django/core/files/storage/filesystem.py", line 100, in _save

    os.makedirs(directory, exist_ok=True)

  File "<frozen os>", line 225, in makedirs

PermissionError: [Errno 13] Permission denied: '/home/nonroot/pdfding/media/1'

**Comment by mrmn2** [comment]
I am not sure about your setup but using
```
  volumes:
    - media:/home/nonroot/pdfding/media:Z
```
instead of
```
  volumes:
    - media:/home/nonroot/pdfding/media
```
might do the trick.

**Comment by econcepcion** [comment]
Thanks for the reply.  I tried that but still getting the error.

Screen error "Server Error (500)"

When I look at permissions, they all show nonroot:nonroot

I am using Debian.

**Comment by mrmn2** [comment]
Hm, that's strange I have selinux enabled on my system and I get the permission denied error when not adding `:Z`. When added everything works fine.

Can you run `sestatus` on your host (not inside the container) and paste the result?

Also can you temporarily remove 
```
  volumes:
    - media:/home/nonroot/pdfding/media
```
and check if it is now working? 
31 Dec 2024, 17:03 by ***@***.***:

**Comment by sganarel** [comment]
Hello, I Have the same issue.
Do you plan to user environment variables for UID & GUID in the docker compose ?
It could resolve the permissions on the volume we choose.

**Comment by mrmn2** [comment]
@sganarel @econcepcion I think I have understood the problem. Can you verify that your UID and GID of your host system are different from `1000`? (You can use the id command). 

Can you also execute `ls -lan pdfding` inside the shell of the container and paste the contents? 

The problem is caused that the host system has a different UID + GID compared to the container. As the media directory is not existing in the container, when creating the media volume the host UID/GID will be used. The good news is that this will be fixed if I am not mistaken with the next version. In this version the media directory will already exists in the image to to a pdf file used in the demo mode. Therefore, the host's UID/GID will not be used. I ran some tests and at least on my system this holds true.

**Comment by econcepcion** [comment]
I was able to upload a pdf after creating the folder for the first user manually.

had to login as root, create directory 1, then chown back to nonroot.

sh: sestatus: not found

**Comment by econcepcion** [comment]
> Hello, I Have the same issue. Do you plan to user environment variables for UID & GUID in the docker compose ? It could resolve the permissions on the volume we choose.

I did use both but still not working

**Comment by econcepcion** [comment]
> @sganarel @econcepcion I think I have understood the problem. Can you verify that your UID and GID of your host system are different from `1000`? (You can use the id command).
> 
> Can you also execute `ls -lan pdfding` inside the shell of the container and paste the contents?
> 
> The problem is caused that the host system has a different UID + GID compared to the container. As the media directory is not existing in the container, when creating the media volume the host UID/GID will be used. The good news is that this will be fixed in the next version if I am not mistaken. In this version the media directory will already existsin the image due to a pdf file used in the demo mode. Therefore, the host's UID/GID will not be used. I ran some tests and at least on my system this holds true.



drwxr-sr-x    1 1000     1000          4096 Dec 25 08:11 .
drwxr-sr-x    1 1000     1000          4096 Jan  1 00:56 ..
drwxr-xr-x    1 1000     1000          4096 Dec 25 08:11 admin
drwxr-xr-x    1 1000     1000          4096 Dec 25 08:11 backup
drwxr-xr-x    1 1000     1000          4096 Dec 31 17:27 base
drwxr-xr-x    1 1000     1000          4096 Dec 25 08:11 core
drwxr-xr-x    1 1000     1000          4096 Dec 31 17:27 db
-rwxr-xr-x    1 1000     1000           680 Dec 25 08:10 manage.py
drwxr-xr-x    1 1000     1000          4096 Dec 25 08:11 pdf
drwxr-xr-x    2 1000     1000          4096 Dec 25 08:12 static
drwxr-xr-x    6 1000     1000          4096 Dec 25 08:11 staticfiles
drwxr-xr-x    8 1000     1000          4096 Dec 25 08:10 templates
drwxr-xr-x    1 1000     1000          4096 Dec 25 08:11 users

**Comment by econcepcion** [comment]
SO i got it fully fuinctional by logging into container and running  

chown -R nonroot:nonroot nonroot/

**Comment by mrmn2** [comment]
Perfect! Thanks to bringing this issue to my attention. The next version will likely fix this problem, so future users won't encounter the same problem. 

If you like PdfDing please consider giving it a star. Thanks!

**Comment by sganarel** [comment]
Hello MrMN2,

When do you plan to release a version to use the UID/GID of our choice ?
I still have the permission error (when creating the directory ../media/1 during upload ...) with latest version.

Thanks you.

**Comment by mrmn2** [comment]
Hi, have you deleted the volume, that was created with the old version? If not you will need to remove it as it still has the old permission issue. I am not sure how the `media` volume is named on your machine, use `docker volume ls` to figure out the name. The volume name should be something like `deploy_media`. Afterwards, use `docker volume remove <media_volume_name>`. Now you can proceed with docker compose as usual.

At least on my end I am now able to run PdfDing when host has a different UID.
